
server: 
  port: 8181
  
management:
 endpoints:
    web:
      exposure:
        include: '*'
        
spring:
  profiles:
    active: native
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gayanJeevaka/spring-config-server.git
          search-paths:
          - '*service'
            